/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import poo.ClasesDominio.*;

/**
 *
 * @author Alejandro
 */
public class GestionSeries extends javax.swing.JFrame {
   
    private static ArrayList <Serie> series = new ArrayList<>();
    private static ArrayList <Capitulo> capitulos = new ArrayList<>();   
    
    DefaultListModel modelo2=new DefaultListModel();
    DefaultListModel modelo = new DefaultListModel();
    
    public GestionSeries() {
        initComponents();
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        setLocationRelativeTo(null);
        jSeries.setModel(modelo);
        jCapitulos.setModel(modelo2);        
        
        GuardarLeerFicheros.cargarDatosSeries();
        series = GuardarLeerFicheros.obtenerArraySeries();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSeries = new javax.swing.JList<>();
        btnAnnadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jTemporadas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jAnno = new javax.swing.JTextField();
        jTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jActor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jGenero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSinopsis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jImagen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        labelErrorRuta = new javax.swing.JLabel();
        jTituloCap = new javax.swing.JTextField();
        jDuracionCap = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCapitulos = new javax.swing.JList<>();
        jAnnadirCap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jSeries.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jSeriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jSeries);

        btnAnnadir.setText("Añadir");
        btnAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnadirActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Temporadas");

        jLabel6.setText("Año");

        jLabel3.setText("Titulo");

        jLabel7.setText("Actor");

        jLabel5.setText("Genero");

        jLabel2.setText("Sinopsis");

        jImagen.setToolTipText("");
        jImagen.setToolTipText("Introduzca el nombre del archivo y la extensión");

        jLabel8.setText("Imagen");

        labelErrorRuta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelErrorRuta.setForeground(new java.awt.Color(255, 0, 0));
        labelErrorRuta.setText("Error al introducir la ruta...");
        labelErrorRuta.setOpaque(true);
        labelErrorRuta.setVisible(false);

        jCapitulos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jCapitulosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jCapitulos);

        jAnnadirCap.setText("Añadir Capitulo");
        jAnnadirCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnnadirCapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAnnadir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMostrar)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTituloCap, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDuracionCap, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jAnnadirCap, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jActor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelErrorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)))
                    .addComponent(jImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelErrorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jActor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnnadir)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnMostrar)
                            .addComponent(jAnnadirCap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTituloCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDuracionCap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnadirActionPerformed
        
        String temporadas=jTemporadas.getText();
        String titulo=jTitulo.getText();
        String sinopsis=jSinopsis.getText();
        String genero=jGenero.getText();
        String anno=jAnno.getText();
        String actor=jActor.getText();
        String titulocap=jTituloCap.getText();
        String duracioncap=jDuracionCap.getText();
        ImageIcon icon = new ImageIcon("imagenes/"+jImagen.getText());
        
        if (icon.getIconWidth() != -1) {
            
            jImagen.setText("");
            Serie serie=new Serie(temporadas,capitulos,titulo,sinopsis,genero,anno,actor,icon, "");
            series.add(serie);
            GuardarLeerFicheros.guardarDatosSeries();
            
        } else {
            
            System.out.println("Error de ruta");
            labelErrorRuta.setVisible(true);
            jImagen.setText("");
        }
        
    }//GEN-LAST:event_btnAnnadirActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        modelo.removeAllElements();
        modelo2.removeAllElements();
        for(int i=0;i<series.size();i++){
            modelo.addElement(series.get(i).getTitulo());
            
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void jSeriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jSeriesValueChanged
        int selection = jSeries.getSelectedIndex();
        modelo2.removeAllElements();
        
        if (selection!=-1) {
            Serie s = series.get(selection);
            capitulos=s.getCapitulos();
            jActor.setText(s.getActores());
            jAnno.setText(s.getAnno());                        
            jGenero.setText(s.getGenero());
            jTitulo.setText(s.getTitulo());
            jSinopsis.setText(s.getSinopsis());
            jPhoto.setIcon(s.getImagen());
            jTemporadas.setText(s.getTemporadas());
            for(Capitulo c:capitulos){
                modelo2.addElement(c.getTitulo());                
            }
        }
    }//GEN-LAST:event_jSeriesValueChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int selection = jSeries.getSelectedIndex();
        Serie s = series.get(selection);
        
        ImageIcon icon = new ImageIcon("imagenes/"+jImagen.getText());
        ImageIcon errorIcon = s.getImagen();
        
        s.setImagen(icon);
        
        if (icon.getIconWidth() != -1) {
            s.setImagen(icon);
            jImagen.setText("");
        } else {
            System.out.println("Error de ruta");
            labelErrorRuta.setVisible(true);
            jImagen.setText("");
            s.setImagen(errorIcon);
        }
        
        s.setActores(jActor.getText());
        s.setAño(jAnno.getText());
        s.setTemporadas(jTemporadas.getText());
        s.setGenero(jGenero.getText());
        s.setSinopsis(jSinopsis.getText());
        s.setTitulo(jTitulo.getText());
        s.setCapitulos(capitulos);
        
               
        series.remove(selection);
        series.add(s);
        
        GuardarLeerFicheros.guardarDatosSeries();
        
        modelo.removeAllElements();
        jActor.setText("");
        jAnno.setText("");
        jTemporadas.setText("");
        jGenero.setText("");
        jTitulo.setText("");
        jSinopsis.setText("");
        jTituloCap.setText("");
        jDuracionCap.setText("");
        jPhoto.setIcon(null);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selection = jSeries.getSelectedIndex();
        series.remove(selection);
        modelo.removeAllElements();
        modelo2.removeAllElements();
        jActor.setText("");
        jAnno.setText("");
        jTemporadas.setText("");
        jGenero.setText("");
        jImagen.setText("");
        jTitulo.setText("");
        jSinopsis.setText("");
        jPhoto.setIcon(null);
        GuardarLeerFicheros.guardarDatosSeries();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        labelErrorRuta.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jCapitulosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jCapitulosValueChanged
        int capit=jCapitulos.getSelectedIndex();
        if (capit!=-1) {
            Capitulo c = capitulos.get(capit);
            jDuracionCap.setText(c.getDuracion());
            jTituloCap.setText(c.getTitulo());
        }
    }//GEN-LAST:event_jCapitulosValueChanged
    //Metodo para añadir capitulo
    private void jAnnadirCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnnadirCapActionPerformed
        String titulocap=jTituloCap.getText();
        String duracioncap=jDuracionCap.getText();
        jTituloCap.setText("");
        jDuracionCap.setText("");
        
        Capitulo cap=new Capitulo(titulocap,duracioncap);
        capitulos.add(cap);
        
        
    }//GEN-LAST:event_jAnnadirCapActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JTextField jActor;
    private javax.swing.JButton jAnnadirCap;
    private javax.swing.JTextField jAnno;
    private javax.swing.JList<String> jCapitulos;
    private javax.swing.JTextField jDuracionCap;
    private javax.swing.JTextField jGenero;
    private javax.swing.JTextField jImagen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jSeries;
    private javax.swing.JTextField jSinopsis;
    private javax.swing.JTextField jTemporadas;
    private javax.swing.JTextField jTitulo;
    private javax.swing.JTextField jTituloCap;
    private javax.swing.JLabel labelErrorRuta;
    // End of variables declaration//GEN-END:variables
}
