/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import poo.ClasesDominio.*;

/**
 *
 * @author RiCh_LiKe
 */
public class PanelListaFav extends javax.swing.JFrame {

    private static ArrayList <Pelicula> peliculasFav = new ArrayList<>();
    private static ArrayList <Serie> seriesFav = new ArrayList<>();
    private static ArrayList <JLabel> imagenesLabels = new ArrayList<>();
    private static String dniTemp;
    
    public PanelListaFav() {
        initComponents();
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        setVisible(true);
        
        
        // Metemos todas las labels donde van a ir las imagenes en un array
        
        imagenesLabels.clear();
        
        imagenesLabels.add(labelImagen1);
        imagenesLabels.add(labelImagen2);
        imagenesLabels.add(labelImagen3);
        imagenesLabels.add(labelImagen4);
        imagenesLabels.add(labelImagen5);
        imagenesLabels.add(labelImagen6);
        imagenesLabels.add(labelImagen7);
        imagenesLabels.add(labelImagen8);
        imagenesLabels.add(labelImagen9);
        imagenesLabels.add(labelImagen10);
        imagenesLabels.add(labelImagen11);
        imagenesLabels.add(labelImagen12);
        imagenesLabels.add(labelImagen13);
        imagenesLabels.add(labelImagen14);
        imagenesLabels.add(labelImagen15);
        imagenesLabels.add(labelImagen16);
        imagenesLabels.add(labelImagen17);
        imagenesLabels.add(labelImagen18);
        
        GuardarLeerFicheros.cargarPeliculasListaFav(leerDniTemp());
        peliculasFav = GuardarLeerFicheros.obtenerArrayPeliculasFav();
        
        GuardarLeerFicheros.cargarSeriesListaFav(leerDniTemp());
        seriesFav = GuardarLeerFicheros.obtenerArraySeriesFav();
        
        int contador = 0;
        
        for (Pelicula pel: peliculasFav) {
            
            imagenesLabels.get(contador).setIcon(pel.getImagen());
            imagenesLabels.get(contador).setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            contador ++;
            
        }
        
        for (Serie ser: seriesFav) {
            
            System.out.println("Poniendo series");
            imagenesLabels.get(contador).setIcon(ser.getImagen());
            imagenesLabels.get(contador).setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            contador ++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        panelTransparente1 = new poo.Interfaces.PanelTransparente();
        labelTitulo1 = new javax.swing.JLabel();
        labelImagen1 = new javax.swing.JLabel();
        labelImagen2 = new javax.swing.JLabel();
        labelImagen3 = new javax.swing.JLabel();
        labelImagen4 = new javax.swing.JLabel();
        labelImagen5 = new javax.swing.JLabel();
        labelImagen6 = new javax.swing.JLabel();
        labelImagen7 = new javax.swing.JLabel();
        labelImagen8 = new javax.swing.JLabel();
        labelImagen9 = new javax.swing.JLabel();
        labelImagen10 = new javax.swing.JLabel();
        labelImagen11 = new javax.swing.JLabel();
        labelImagen12 = new javax.swing.JLabel();
        labelImagen13 = new javax.swing.JLabel();
        labelImagen14 = new javax.swing.JLabel();
        labelImagen15 = new javax.swing.JLabel();
        labelImagen16 = new javax.swing.JLabel();
        labelImagen17 = new javax.swing.JLabel();
        labelImagen18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        ImageIcon icon = new ImageIcon("imagenes/logo.png");

        labelLogo.setIcon(icon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(830, Short.MAX_VALUE))
        );

        panelTransparente1.setBackground(new java.awt.Color(51, 51, 51));
        panelTransparente1.setForeground(new java.awt.Color(255, 255, 255));

        labelTitulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo1.setText("PELICULAS Y SERIES:");

        labelImagen1.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen1.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen2.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen2.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen3.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen3.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen4.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen4.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen5.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen5.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen6.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen6.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen7.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen7.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen8.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen8.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen9.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen9.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen10.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen10.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen11.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen11.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen12.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen12.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen13.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen13.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen14.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen14.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen15.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen15.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen16.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen16.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen17.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen17.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelImagen18.setBackground(new java.awt.Color(255, 255, 255));
        labelImagen18.setForeground(new java.awt.Color(255, 255, 255));
        labelImagen18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelTransparente1Layout = new javax.swing.GroupLayout(panelTransparente1);
        panelTransparente1.setLayout(panelTransparente1Layout);
        panelTransparente1Layout.setHorizontalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImagen7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(labelImagen13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImagen8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelImagen14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImagen9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelImagen15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelImagen16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addComponent(labelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(labelImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(labelImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(labelImagen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImagen5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(labelImagen11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImagen17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImagen6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(labelImagen12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImagen18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addComponent(labelTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelTransparente1Layout.setVerticalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelImagen6, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(labelImagen5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelImagen12, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(labelImagen11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelImagen13, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(labelImagen14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelImagen18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(panelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(panelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    
    public static String leerDniTemp() {
        String dni = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader("ficheros/archivoTemporal.dat"));
            String temp = "";
            String bfRead;
            while ((bfRead = br.readLine()) != null) {
                temp = temp + bfRead;
            }
            dni = temp;
            
        } catch (Exception e) {
        }
        return dni;
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JLabel labelImagen10;
    private javax.swing.JLabel labelImagen11;
    private javax.swing.JLabel labelImagen12;
    private javax.swing.JLabel labelImagen13;
    private javax.swing.JLabel labelImagen14;
    private javax.swing.JLabel labelImagen15;
    private javax.swing.JLabel labelImagen16;
    private javax.swing.JLabel labelImagen17;
    private javax.swing.JLabel labelImagen18;
    private javax.swing.JLabel labelImagen2;
    private javax.swing.JLabel labelImagen3;
    private javax.swing.JLabel labelImagen4;
    private javax.swing.JLabel labelImagen5;
    private javax.swing.JLabel labelImagen6;
    private javax.swing.JLabel labelImagen7;
    private javax.swing.JLabel labelImagen8;
    private javax.swing.JLabel labelImagen9;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelTitulo1;
    private poo.Interfaces.PanelTransparente panelTransparente1;
    // End of variables declaration//GEN-END:variables
}
