/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import javax.swing.ImageIcon;
import poo.ClasesDominio.Cliente;
import poo.ClasesDominio.Suscripcion;


/**
 *
 * @author RiCh_LiKe
 */
public class PanelSuscrispcion extends javax.swing.JFrame {

    Cliente client;
    
    double susBasica = 8.99;
    double susEstandar = 11.99;
    double susPremium = 15.99;
    
    LocalDateTime time = LocalDateTime.now();
    LocalDate fechaSuscripcion  = LocalDate.of(time.getYear(), time.getMonth(), time.getDayOfMonth()); 
    
    public PanelSuscrispcion() {
        initComponents();
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        setLocationRelativeTo(null);
    }
    
    public void volverInicio(){
        
        PanelInicioSesion pis = new PanelInicioSesion();
        pis.setVisible(true);
        this.dispose();
    }
    
    public void guardarDatosSuscripcion(String dni, Suscripcion sus) {
        try (FileOutputStream fosPer = new FileOutputStream("ficheros/suscripciones/"+dni+".dat");
            ObjectOutputStream oosPer = new ObjectOutputStream(fosPer)){
            
            oosPer.writeObject(sus);
            System.out.println("Suscripcion guardada correctamente");
            

        } catch (IOException ioe) {
            System.out.println("Error de IO: " + ioe.getMessage());
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo1 = new poo.Interfaces.Fondo();
        jPanel1 = new javax.swing.JPanel();
        panelTransparente1 = new poo.Interfaces.PanelTransparente();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBasico = new javax.swing.JButton();
        btnEstandar = new javax.swing.JButton();
        btnPremium = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setOpaque(false);

        panelTransparente1.setBackground(new java.awt.Color(51, 51, 51));
        panelTransparente1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ImageIcon icon = new ImageIcon("imagenes/logo.png");

        labelTitulo.setIcon(icon);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Seleccione el tipo de suscripción");

        btnBasico.setBackground(new java.awt.Color(230, 0, 0));
        btnBasico.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBasico.setText("Básico");
        btnBasico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBasico.setBorderPainted(false);
        btnBasico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBasico.setMaximumSize(new java.awt.Dimension(110, 110));
        btnBasico.setMinimumSize(new java.awt.Dimension(110, 110));
        btnBasico.setPreferredSize(new java.awt.Dimension(110, 110));
        btnBasico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBasicoMouseClicked(evt);
            }
        });
        btnBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasicoActionPerformed(evt);
            }
        });

        btnEstandar.setBackground(new java.awt.Color(230, 0, 0));
        btnEstandar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEstandar.setText("Estandar");
        btnEstandar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEstandar.setBorderPainted(false);
        btnEstandar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstandar.setMaximumSize(new java.awt.Dimension(110, 110));
        btnEstandar.setMinimumSize(new java.awt.Dimension(110, 110));
        btnEstandar.setPreferredSize(new java.awt.Dimension(110, 110));
        btnEstandar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstandarMouseClicked(evt);
            }
        });
        btnEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstandarActionPerformed(evt);
            }
        });

        btnPremium.setBackground(new java.awt.Color(230, 0, 0));
        btnPremium.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPremium.setText("Premium");
        btnPremium.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPremium.setBorderPainted(false);
        btnPremium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPremium.setMaximumSize(new java.awt.Dimension(110, 110));
        btnPremium.setMinimumSize(new java.awt.Dimension(110, 110));
        btnPremium.setPreferredSize(new java.awt.Dimension(110, 110));
        btnPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPremiumMouseClicked(evt);
            }
        });
        btnPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremiumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("8.99$");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("15.99$");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("11.99$");

        javax.swing.GroupLayout panelTransparente1Layout = new javax.swing.GroupLayout(panelTransparente1);
        panelTransparente1.setLayout(panelTransparente1Layout);
        panelTransparente1Layout.setHorizontalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addGap(67, 67, 67))
        );
        panelTransparente1Layout.setVerticalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(panelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(panelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstandarActionPerformed

    private void btnPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPremiumActionPerformed

    private void btnBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBasicoActionPerformed

    private void btnBasicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBasicoMouseClicked
        
        Suscripcion sus = new Suscripcion(fechaSuscripcion, client, susBasica);         // Se crea la suscripción
        String dni = client.getDni();                                                   // Se saca el dni del cliente para ponerlo de nombre al fichero
        
        guardarDatosSuscripcion(dni, sus);
        volverInicio();
    }//GEN-LAST:event_btnBasicoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnEstandarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstandarMouseClicked

        Suscripcion sus = new Suscripcion(fechaSuscripcion, client, susEstandar);         // Se crea la suscripción
        String dni = client.getDni();                                                     // Se saca el dni del cliente para ponerlo de nombre al fichero
        
        guardarDatosSuscripcion(dni, sus);
        
        volverInicio();
    }//GEN-LAST:event_btnEstandarMouseClicked

    private void btnPremiumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPremiumMouseClicked
        
        Suscripcion sus = new Suscripcion(fechaSuscripcion, client, susPremium);         // Se crea la suscripción
        String dni = client.getDni();                                                    // Se saca el dni del cliente para ponerlo de nombre al fichero
        
        guardarDatosSuscripcion(dni, sus);
        
        volverInicio();
    }//GEN-LAST:event_btnPremiumMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBasico;
    private javax.swing.JButton btnEstandar;
    private javax.swing.JButton btnPremium;
    private poo.Interfaces.Fondo fondo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitulo;
    private poo.Interfaces.PanelTransparente panelTransparente1;
    // End of variables declaration//GEN-END:variables
}
