/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import poo.ClasesDominio.Cliente;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import poo.ClasesDominio.Administrador;
import poo.ClasesDominio.GuardarLeerFicheros;

/**
 *
 * @author RiCh_LiKe
 */
public class PanelInicioSesion extends javax.swing.JFrame {
    
    Administrador admin = new Administrador("admin@javaflix.com", "admin");
    
    public PanelInicioSesion() {
        
        initComponents();
        
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo1 = new poo.Interfaces.Fondo();
        panelBase = new javax.swing.JPanel();
        panelInicioSesion = new poo.Interfaces.PanelTransparente();
        labelTitulo = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JLabel();
        labelCrearCuenta = new javax.swing.JLabel();
        labelSubTitulo = new javax.swing.JLabel();
        CorreoInvalido = new javax.swing.JLabel();
        ContrasenaInvalido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBase.setOpaque(false);

        panelInicioSesion.setBackground(new java.awt.Color(51, 51, 51));
        panelInicioSesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ImageIcon icon = new ImageIcon("imagenes/logo.png");

        labelTitulo.setIcon(icon);

        labelCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        labelCorreo.setText("Correo:");

        labelContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena.setText("Contraseña:");

        txtCorreo.setBackground(new java.awt.Color(102, 102, 102));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtContrasena.setBackground(new java.awt.Color(102, 102, 102));
        txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasena.setBorder(null);
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarKeyPressed(evt);
            }
        });

        labelCrearCuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        labelCrearCuenta.setText("Crear una cuenta");
        labelCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCrearCuentaMouseClicked(evt);
            }
        });

        labelSubTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelSubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelSubTitulo.setText("Iniciar sesión");
        labelSubTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSubTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSubTituloMouseClicked(evt);
            }
        });

        CorreoInvalido.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CorreoInvalido.setForeground(new java.awt.Color(255, 0, 0));
        CorreoInvalido.setText("El correo introducido no es valido");
        CorreoInvalido.setVisible(false);

        ContrasenaInvalido.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ContrasenaInvalido.setForeground(new java.awt.Color(255, 0, 0));
        ContrasenaInvalido.setText("La contraseña introducida no es valida");
        ContrasenaInvalido.setVisible(false);

        javax.swing.GroupLayout panelInicioSesionLayout = new javax.swing.GroupLayout(panelInicioSesion);
        panelInicioSesion.setLayout(panelInicioSesionLayout);
        panelInicioSesionLayout.setHorizontalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContrasenaInvalido)
                    .addComponent(CorreoInvalido)
                    .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCorreo)
                        .addComponent(labelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioSesionLayout.createSequentialGroup()
                            .addComponent(labelCrearCuenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                            .addComponent(btnConfirmar))
                        .addComponent(txtContrasena)
                        .addComponent(labelSubTitulo)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInicioSesionLayout.setVerticalGroup(
            panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioSesionLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSubTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorreoInvalido)
                .addGap(26, 26, 26)
                .addComponent(labelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContrasenaInvalido)
                .addGap(25, 25, 25)
                .addGroup(panelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelSubTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSubTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSubTituloMouseClicked

    private void labelCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCrearCuentaMouseClicked
        irRegistro();       // Lleva hacia la pagina de registro
    }//GEN-LAST:event_labelCrearCuentaMouseClicked

    @SuppressWarnings("unchecked")
    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
                
        if (admin.getCorreo().equals(txtCorreo.getText()) && admin.getClave().equals(txtContrasena.getText())) {
            
            PanelAdmin pa = new PanelAdmin();
            pa.setVisible(true);
            this.dispose();
            
        } else{
            
            CorreoInvalido.setVisible(true);
            ContrasenaInvalido.setVisible(true);
        }

        GuardarLeerFicheros.cargarDatosClientes();
        
        clientes = GuardarLeerFicheros.obtenerArrayClientes(); 
        
        for(Cliente cli:clientes){                              // Comprobar que el usuario y contraseña son validos

            if (cli.getCorreo().equals(txtCorreo.getText()) && cli.getClave().equals(txtContrasena.getText())){  // Comprobar que el correo y contraseña coinciden
                
                guardarDniTemp(cli.getDni());

                PanelUsuario pu = new PanelUsuario();           // Se le permite acceder al panel de usuario
                this.dispose();                                 // Ocultamos el panel de inicio
            } else{

                CorreoInvalido.setVisible(true);
                ContrasenaInvalido.setVisible(true);
            }
        }

    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnConfirmarKeyPressed

    public void irRegistro() {
        
        PanelRegistro p = new PanelRegistro(this);
        p.setVisible(true);
        this.dispose();
    }
    
    public static void guardarDniTemp(String dni) {
        try (PrintWriter salida= new PrintWriter(new BufferedWriter(new FileWriter("ficheros/archivoTemporal.dat")))) {
            salida.println(dni);
            
        } catch (IOException ioe) {
            System.out.println("Error IO: "+ioe.toString());
        }
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContrasenaInvalido;
    private javax.swing.JLabel CorreoInvalido;
    private javax.swing.JLabel btnConfirmar;
    private poo.Interfaces.Fondo fondo1;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelCrearCuenta;
    private javax.swing.JLabel labelSubTitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelBase;
    private poo.Interfaces.PanelTransparente panelInicioSesion;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

    private static ArrayList <Cliente> clientes = new ArrayList<>();
  
}
