/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import poo.ClasesDominio.*;

/**
 *
 * @author RiCh_LiKe
 */

public class PanelCuenta extends javax.swing.JFrame {
    
    private static String dniTemp;
    private static Suscripcion sus = new Suscripcion();
    
    public PanelCuenta() {
        initComponents();
        setLocationRelativeTo(null);
        
        GuardarLeerFicheros.cargarDatosSuscripcion(leerDniTemp());
        sus = GuardarLeerFicheros.obtenerSuscripcion();
        
        Double precioSuscripcion = sus.getPrecioSuscripcion();
            
        Double saldo = sus.getCliente().getTarjetaCredito().getSaldo();
            
        jNumTarjeta.setText(sus.getCliente().getTarjetaCredito().getNumero());
        jNombre.setText(sus.getCliente().getNombre());
        jClave.setText(sus.getCliente().getClave());
        jSaldo.setText(saldo.toString());
        jDni.setText(sus.getCliente().getDni());
        jCorreo.setText(sus.getCliente().getCorreo());
        jFechaCaducidad.setText(sus.getCliente().getTarjetaCredito().getFechaCaducidad().toString());
            
        jTipoSuscripcion.setText(precioSuscripcion.toString());
        jFechaSus.setText(sus.getFechaSuscripcion().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jNumTarjeta = new javax.swing.JTextField();
        jDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jClave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFechaCaducidad = new javax.swing.JTextField();
        jTipoSuscripcion = new javax.swing.JTextField();
        jFechaSus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnPagoSus = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jNombre.setEnabled(false);

        jLabel4.setText("Nombre");

        jLabel6.setText("Numero de Trajeta");

        jNumTarjeta.setEnabled(false);

        jDni.setEnabled(false);

        jLabel3.setText("Dni");

        jLabel7.setText("Fecha de Caducidad");

        jSaldo.setEnabled(false);

        jLabel5.setText("Saldo");

        jCorreo.setEnabled(false);

        jLabel2.setText("Correo");

        jClave.setEnabled(false);

        jLabel1.setText("Contraseña");

        jLabel8.setText("Tipo de Suscripción");

        jFechaCaducidad.setEnabled(false);

        jTipoSuscripcion.setEnabled(false);

        jFechaSus.setEnabled(false);

        jLabel9.setText("Fecha de suscripción");

        btnPagoSus.setText("Pago de suscripción");
        btnPagoSus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagoSus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPagoSusMouseClicked(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTipoSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFechaSus, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagoSus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDni, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jClave, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFechaSus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTipoSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagoSus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoSusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagoSusMouseClicked
        // TODO add your handling code here:
        Double saldoInicial = sus.getCliente().getTarjetaCredito().getSaldo();
        
        System.out.println(validarCaducidad());
        System.out.println(validarSaldo());
        
        if (validarCaducidad() && validarSaldo()) {
            
            
            sus.getCliente().getTarjetaCredito().setSaldo(saldoInicial-sus.getPrecioSuscripcion());
            GuardarLeerFicheros.guardarDatosSuscripcion(sus.getCliente().getDni(), sus);
            
            GuardarLeerFicheros.cargarDatosClientes();
            clientes = GuardarLeerFicheros.obtenerArrayClientes();
            
            for(Cliente cli:clientes){
                if (cli.getDni().equals(sus.getCliente().getDni())){
                    cli.getTarjetaCredito().setSaldo(saldoInicial-sus.getPrecioSuscripcion());
                    
                }
            }
            GuardarLeerFicheros.guardarDatosClientes();
            
        }
        
        btnPagoSus.setEnabled(false);
    }//GEN-LAST:event_btnPagoSusMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
        GuardarLeerFicheros.cargarDatosSuscripcion(leerDniTemp());
        sus = GuardarLeerFicheros.obtenerSuscripcion();
        
        Double precioSuscripcion = sus.getPrecioSuscripcion();
            
        Double saldo = sus.getCliente().getTarjetaCredito().getSaldo();
            
        jNumTarjeta.setText(sus.getCliente().getTarjetaCredito().getNumero());
        jNombre.setText(sus.getCliente().getNombre());
        jClave.setText(sus.getCliente().getClave());
        jSaldo.setText(saldo.toString());
        jDni.setText(sus.getCliente().getDni());
        jCorreo.setText(sus.getCliente().getCorreo());
        jFechaCaducidad.setText(sus.getCliente().getTarjetaCredito().getFechaCaducidad().toString());
            
        jTipoSuscripcion.setText(precioSuscripcion.toString());
        jFechaSus.setText(sus.getFechaSuscripcion().toString());
    }//GEN-LAST:event_btnActualizarMouseClicked

    /**
     * @param args the command line arguments
     */

    
    public static boolean validarSaldo() {
        return sus.getCliente().getTarjetaCredito().getSaldo() >= sus.getPrecioSuscripcion();
    }
    
    public static boolean validarCaducidad() {
        return sus.getCliente().getTarjetaCredito().getFechaCaducidad().isAfter(sus.getFechaSuscripcion());
    }
    
    public static String leerDniTemp() {
        String dni = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader("ficheros/archivoTemporal.dat"));
            String temp = "";
            String bfRead;
            while ((bfRead = br.readLine()) != null) {
                temp = temp + bfRead;
            }
            dni = temp;
            
        } catch (Exception e) {
        }
        return dni;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnPagoSus;
    private javax.swing.JTextField jClave;
    private javax.swing.JTextField jCorreo;
    private javax.swing.JTextField jDni;
    private javax.swing.JTextField jFechaCaducidad;
    private javax.swing.JTextField jFechaSus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombre;
    private javax.swing.JTextField jNumTarjeta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jSaldo;
    private javax.swing.JTextField jTipoSuscripcion;
    // End of variables declaration//GEN-END:variables

    private static ArrayList <Cliente> clientes = new ArrayList<>();
}
