/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import poo.ClasesDominio.Cliente;
import poo.ClasesDominio.Pelicula;
import poo.ClasesDominio.Serie;

/**
 *
 * @author RiCh_LiKe
 */
public class PanelAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGesPeliculas = new javax.swing.JButton();
        btnGesSeries = new javax.swing.JButton();
        btnGesUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnGesPeliculas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGesPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        btnGesPeliculas.setText("Gestión de peliculas");
        btnGesPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGesPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGesPeliculasMouseClicked(evt);
            }
        });

        btnGesSeries.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGesSeries.setForeground(new java.awt.Color(255, 255, 255));
        btnGesSeries.setText("Gestión de series");
        btnGesSeries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGesSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGesSeriesMouseClicked(evt);
            }
        });

        btnGesUsuarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGesUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnGesUsuarios.setText("Gestión de usuarios");
        btnGesUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGesUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGesUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGesSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGesPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnGesPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGesSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGesPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesPeliculasMouseClicked
        // TODO add your handling code here:
        GestionPeliculas gp = new GestionPeliculas();
        gp.setVisible(true);
    }//GEN-LAST:event_btnGesPeliculasMouseClicked

    private void btnGesSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesSeriesMouseClicked
        // TODO add your handling code here:
        GestionSeries gs = new GestionSeries();
        gs.setVisible(true);
    }//GEN-LAST:event_btnGesSeriesMouseClicked

    private void btnGesUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGesUsuariosMouseClicked
        // TODO add your handling code here:
        GestionUsuarios gu = new GestionUsuarios();
        gu.setVisible(true);
    }//GEN-LAST:event_btnGesUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGesPeliculas;
    private javax.swing.JButton btnGesSeries;
    private javax.swing.JButton btnGesUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static ArrayList <Cliente> clientes = new ArrayList<>();
    private static ArrayList <Pelicula> peliculas = new ArrayList<>();
    private static ArrayList <Serie> series = new ArrayList<>();

}
