/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import poo.ClasesDominio.GuardarLeerFicheros;
import poo.ClasesDominio.Pelicula;
import poo.ClasesDominio.Serie;
import static poo.Interfaces.PanelBusquedaSerie.leerDniTemp;

/**
 *
 * @author Alejandro
 */
public class PanelBusquedaPelis extends javax.swing.JFrame {
    DefaultListModel modelo = new DefaultListModel();
    private static ArrayList <Pelicula> peliculas = new ArrayList<>();
    private static ArrayList <Pelicula> peliculasFav = new ArrayList<>();
    private static String dniTemp;
    /**
     * Creates new form Buscar
     */
    public PanelBusquedaPelis() {
        initComponents();
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        setLocationRelativeTo(null);
        
        GuardarLeerFicheros.cargarDatosPeliculas();
        peliculas = GuardarLeerFicheros.obtenerArrayPeliculas();
        ordenarAnno();
        listaBusqueda.setModel(modelo);
        
        GuardarLeerFicheros.cargarPeliculasListaFav(leerDniTemp());
        peliculasFav = GuardarLeerFicheros.obtenerArrayPeliculasFav();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelTransparente1 = new poo.Interfaces.PanelTransparente();
        btnBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaBusqueda = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDirector = new javax.swing.JLabel();
        jAnno = new javax.swing.JLabel();
        jDuracion = new javax.swing.JLabel();
        jActor = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jGenero = new javax.swing.JLabel();
        jImagen = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        btnAddFav = new javax.swing.JButton();
        btnCalificar = new javax.swing.JButton();
        jPuntuacion = new javax.swing.JTextField();
        jPuntuacion2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSinopsis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelBase.setBackground(new java.awt.Color(51, 51, 51));

        panelTransparente1.setBackground(new java.awt.Color(153, 153, 153));
        panelTransparente1.setOpaque(false);

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        listaBusqueda.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaBusquedaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaBusqueda);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Filtros", "Sin filtro", "Género", "Actores", "Año"  }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jDirector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDirector.setForeground(new java.awt.Color(255, 255, 255));
        jDirector.setText(" ");

        jAnno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAnno.setForeground(new java.awt.Color(255, 255, 255));
        jAnno.setText(" ");

        jDuracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDuracion.setForeground(new java.awt.Color(255, 255, 255));
        jDuracion.setText(" ");

        jActor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jActor.setForeground(new java.awt.Color(255, 255, 255));
        jActor.setText(" ");

        jTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setText(" ");

        jGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jGenero.setForeground(new java.awt.Color(255, 255, 255));
        jGenero.setText(" ");

        jImagen.setBackground(new java.awt.Color(102, 102, 102));

        ImageIcon icon = new ImageIcon("imagenes/logo.png");

        labelTitulo.setIcon(icon);

        btnAddFav.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFav.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddFav.setText("Añadir Fav.");
        btnAddFav.setBorder(null);
        btnAddFav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddFav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFavMouseClicked(evt);
            }
        });

        btnCalificar.setBackground(new java.awt.Color(255, 255, 255));
        btnCalificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalificar.setText("Calificar:");
        btnCalificar.setBorder(null);
        btnCalificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalificarMouseClicked(evt);
            }
        });

        jPuntuacion2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPuntuacion2.setForeground(new java.awt.Color(255, 255, 255));
        jPuntuacion2.setText(" ");

        jSinopsis.setColumns(20);
        jSinopsis.setRows(5);
        jSinopsis.setBorder(null);
        jSinopsis.setEnabled(false);
        jScrollPane2.setViewportView(jSinopsis);

        javax.swing.GroupLayout panelTransparente1Layout = new javax.swing.GroupLayout(panelTransparente1);
        panelTransparente1.setLayout(panelTransparente1Layout);
        panelTransparente1Layout.setHorizontalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addComponent(jPuntuacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                                        .addComponent(btnCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPuntuacion, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                                    .addComponent(btnAddFav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jActor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jAnno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(38, 38, 38))))
        );
        panelTransparente1Layout.setVerticalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addComponent(btnAddFav, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalificar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jPuntuacion)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPuntuacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jActor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBaseLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(panelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String busqueda = jTextField1.getText().toLowerCase();

        modelo.removeAllElements();
        for(int i = 0; i < peliculas.size(); i++){
            if((jComboBox1.getSelectedItem().equals("Sin filtro"))&&(peliculas.get(i).getTitulo().toLowerCase().contains(busqueda))){
                modelo.addElement(peliculas.get(i).getTitulo());
            }
            else if((jComboBox1.getSelectedItem().equals("Género"))&&(peliculas.get(i).getGenero().toLowerCase().contains(busqueda))){
                modelo.addElement(peliculas.get(i).getTitulo());
            }
            else if((jComboBox1.getSelectedItem().equals("Actores"))&&(peliculas.get(i).getActores().toLowerCase().contains(busqueda))){
                modelo.addElement(peliculas.get(i).getTitulo());
            }
            else if((jComboBox1.getSelectedItem().equals("Año"))&&(peliculas.get(i).getAnno().toLowerCase().contains(busqueda))){
                modelo.addElement(peliculas.get(i).getTitulo());
            }
        
        }        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void listaBusquedaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaBusquedaValueChanged
        ordenarAnno();
        int selection = listaBusqueda.getSelectedIndex();
        while ((selection != -1)&&(selection<peliculas.size())) {
            Pelicula p = peliculas.get(selection);
            if(!p.getTitulo().contains(jTextField1.getText().toLowerCase())){
                System.out.print("Entra al if");
                selection++;                
            }
            else{
                System.out.print("Entra al else");
               
                jSinopsis.setText("Sinopsis:"+"\n"+p.getSinopsis());            
                jImagen.setIcon(p.getImagen());
                jActor.setText("Actores: "+p.getActores());
                jAnno.setText("Año: "+p.getAnno());
                jDirector.setText("Director: "+p.getDirector());
                jDuracion.setText("Duración: "+p.getDuracion());
                jGenero.setText("Género: "+p.getGenero());
                jTitulo.setText("Titulo: "+p.getTitulo());
                jPuntuacion2.setText("Puntuación: " + p.getPuntuacion());
                 selection++;   
                    }
                
            
        }
    }//GEN-LAST:event_listaBusquedaValueChanged

    private void btnAddFavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFavMouseClicked
        // TODO add your handling code here:
        
        int selection = listaBusqueda.getSelectedIndex();
        if (selection != -1) {
            Pelicula p = peliculas.get(selection);
            
            try {
            
            File file1 = new File("ficheros/listaFav/listaPeliculasFav"+leerDniTemp()+".dat");
            
            // Si los archivos no existen se crean
                if (!file1.exists()) {
                file1.createNewFile();
            }
            } catch (IOException e) {
            e.printStackTrace();
            }
            
            if (peliculasFav.isEmpty()) {
                    peliculasFav.add(p);
                    ordenarAnno();
                    GuardarLeerFicheros.guardarSerieListaFav(leerDniTemp());
            }
            
            for (Pelicula pel: peliculasFav) {
                
                if (!pel.getTitulo().equals(p.getTitulo())) {
                    peliculasFav.add(p);
                    ordenarAnno();
                    GuardarLeerFicheros.guardarPeliculaListaFav(leerDniTemp());
                }
            }
        }
    }//GEN-LAST:event_btnAddFavMouseClicked

    private void btnCalificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalificarMouseClicked
        // TODO add your handling code here:
        int selection = listaBusqueda.getSelectedIndex();
        Double punt;
        
        if (selection != -1) {
            Pelicula p = peliculas.get(selection);
            peliculas.remove(selection);
            
            if (p.getPuntuacion().equals("")) {
                punt = Double.parseDouble(jPuntuacion.getText());
                p.setPuntuacion(jPuntuacion.getText());
                peliculas.add(p);
                ordenarAnno();
                GuardarLeerFicheros.guardarDatosPeliculas();
                jPuntuacion2.setText("Puntuación: "+punt);
                jPuntuacion.setText("");
            } else {
                punt = (Double.parseDouble(p.getPuntuacion()) + Double.parseDouble(jPuntuacion.getText())) / 2;
                p.setPuntuacion(punt.toString());
                peliculas.add(p);
                ordenarAnno();
                GuardarLeerFicheros.guardarDatosPeliculas();
                jPuntuacion2.setText("Puntuación: "+punt);
                jPuntuacion.setText("");
            }
        }
        
    }//GEN-LAST:event_btnCalificarMouseClicked

    /**
     * @param args the command line arguments
     */

    
    public static String leerDniTemp() {
        String dni = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader("ficheros/archivoTemporal.dat"));
            String temp = "";
            String bfRead;
            while ((bfRead = br.readLine()) != null) {
                temp = temp + bfRead;
            }
            dni = temp;
            
        } catch (Exception e) {
        }
        return dni;
    }
    
    public void ordenarAnno() {
        Collections.sort(peliculas, new Comparator<Pelicula>() {            
            @Override
            //Ordenamos el array series por año, de mayor a menor
            public int compare(Pelicula p1, Pelicula p2) {
                    //Comparamos p2 con p1
                    return new Integer(Integer.parseInt(p2.getAnno())).compareTo(new Integer(Integer.parseInt(p1.getAnno())));
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFav;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalificar;
    private javax.swing.JLabel jActor;
    private javax.swing.JLabel jAnno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jDirector;
    private javax.swing.JLabel jDuracion;
    private javax.swing.JLabel jGenero;
    private javax.swing.JLabel jImagen;
    private javax.swing.JTextField jPuntuacion;
    private javax.swing.JLabel jPuntuacion2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jSinopsis;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listaBusqueda;
    private javax.swing.JPanel panelBase;
    private poo.Interfaces.PanelTransparente panelTransparente1;
    // End of variables declaration//GEN-END:variables
}
