/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.Interfaces;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import poo.ClasesDominio.*;

/**
 *
 * @author Alejandro
 */
public class PanelBusquedaSerie extends javax.swing.JFrame {
    
    DefaultListModel modelo=new DefaultListModel();
    DefaultListModel modelo2=new DefaultListModel();

    private static ArrayList <Serie> series = new ArrayList<>();  
    private static ArrayList <Serie> seriesFav = new ArrayList<>();  
    private static ArrayList <Capitulo> capitulos = new ArrayList<>();   
    private static String dniTemp;

    /**
     * Creates new form Buscar
     */
    public PanelBusquedaSerie() {
        initComponents();
        ImageIcon icono = new ImageIcon("imagenes/ventana.jpg");
        setIconImage(icono.getImage());
        setLocationRelativeTo(null);
        
        GuardarLeerFicheros.cargarDatosSeries();
        series = GuardarLeerFicheros.obtenerArraySeries();
        
        GuardarLeerFicheros.cargarSeriesListaFav(leerDniTemp());
        seriesFav = GuardarLeerFicheros.obtenerArraySeriesFav();
        
        listaBusqueda.setModel(modelo);
        listaCapitulos.setModel(modelo2);
        
        //metodo empleado para editar la clase collections y que compare al año entre series
        ordenarAnno();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();
        panelTransparente1 = new poo.Interfaces.PanelTransparente();
        btnBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaBusqueda = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTemporada = new javax.swing.JLabel();
        jAnno = new javax.swing.JLabel();
        jDuracion = new javax.swing.JLabel();
        jActor = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jGenero = new javax.swing.JLabel();
        jImagen = new javax.swing.JLabel();
        jSinopsis = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jTemporadas = new javax.swing.JLabel();
        jDuracionCap = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCapitulos = new javax.swing.JList<>();
        jTemporadas1 = new javax.swing.JLabel();
        btnAddFav = new javax.swing.JButton();
        btnCalificar = new javax.swing.JButton();
        jPuntuacion = new javax.swing.JTextField();
        jPuntuacion3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelBase.setBackground(new java.awt.Color(51, 51, 51));

        panelTransparente1.setBackground(new java.awt.Color(153, 153, 153));
        panelTransparente1.setOpaque(false);

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        listaBusqueda.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaBusquedaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaBusqueda);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Filtros", "Sin filtro", "Género", "Actores", "Año"  }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTemporada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTemporada.setForeground(new java.awt.Color(255, 255, 255));
        jTemporada.setText(" ");

        jAnno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAnno.setForeground(new java.awt.Color(255, 255, 255));
        jAnno.setText(" ");

        jDuracion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDuracion.setForeground(new java.awt.Color(255, 255, 255));
        jDuracion.setText(" ");

        jActor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jActor.setForeground(new java.awt.Color(255, 255, 255));
        jActor.setText(" ");

        jTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setText(" ");

        jGenero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jGenero.setForeground(new java.awt.Color(255, 255, 255));
        jGenero.setText(" ");

        jImagen.setBackground(new java.awt.Color(102, 102, 102));

        jSinopsis.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        jSinopsis.setText(" ");

        ImageIcon icon = new ImageIcon("imagenes/logo.png");

        labelTitulo.setIcon(icon);

        jTemporadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTemporadas.setForeground(new java.awt.Color(255, 255, 255));
        jTemporadas.setText(" ");

        jDuracionCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDuracionCap.setForeground(new java.awt.Color(255, 255, 255));
        jDuracionCap.setText(" ");

        listaCapitulos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listaCapitulos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listaCapitulos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCapitulosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaCapitulos);

        jTemporadas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTemporadas1.setForeground(new java.awt.Color(255, 255, 255));
        jTemporadas1.setText(" Seleccionar capitulo:");

        btnAddFav.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFav.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddFav.setText("Añadir Fav.");
        btnAddFav.setBorder(null);
        btnAddFav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddFav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFavMouseClicked(evt);
            }
        });

        btnCalificar.setBackground(new java.awt.Color(255, 255, 255));
        btnCalificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalificar.setText("Calificar:");
        btnCalificar.setBorder(null);
        btnCalificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalificarMouseClicked(evt);
            }
        });

        jPuntuacion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPuntuacion3.setForeground(new java.awt.Color(255, 255, 255));
        jPuntuacion3.setText(" ");

        javax.swing.GroupLayout panelTransparente1Layout = new javax.swing.GroupLayout(panelTransparente1);
        panelTransparente1.setLayout(panelTransparente1Layout);
        panelTransparente1Layout.setHorizontalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addComponent(btnCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPuntuacion)
                                .addGap(2, 2, 2))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddFav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPuntuacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jActor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDuracionCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTemporadas1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addComponent(jDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(38, 38, 38))
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparente1Layout.setVerticalGroup(
            panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparente1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTemporadas1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparente1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jActor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jDuracionCap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparente1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPuntuacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTransparente1Layout.createSequentialGroup()
                        .addComponent(btnAddFav, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTransparente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnCalificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelTransparente1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPuntuacion)))
                        .addGap(446, 446, 446)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBaseLayout = new javax.swing.GroupLayout(panelBase);
        panelBase.setLayout(panelBaseLayout);
        panelBaseLayout.setHorizontalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBaseLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(panelTransparente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelBaseLayout.setVerticalGroup(
            panelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String busqueda =jTextField1.getText().toLowerCase();

        modelo.removeAllElements();
        for(int i=0;i<series.size();i++){
            if((jComboBox1.getSelectedItem().equals("Sin filtro"))&&(series.get(i).getTitulo().toLowerCase().contains(busqueda))){
                modelo.addElement(series.get(i).getTitulo());
            }
            else if((jComboBox1.getSelectedItem().equals("Género"))&&(series.get(i).getGenero().toLowerCase().contains(busqueda))){
                modelo.addElement(series.get(i).getTitulo());
            }
            else if((jComboBox1.getSelectedItem().equals("Actores"))&&(series.get(i).getActores().toLowerCase().contains(busqueda))){
                modelo.addElement(series.get(i).getTitulo());
            }
            else if((jComboBox1.getSelectedItem().equals("Año"))&&(series.get(i).getAnno().toLowerCase().contains(busqueda))){
                modelo.addElement(series.get(i).getTitulo());
            }
        
        }        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void listaBusquedaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaBusquedaValueChanged

        int selection = listaBusqueda.getSelectedIndex();       
        modelo2.removeAllElements();       
        while ((selection != -1)&&(selection<series.size())) {
            Serie s = series.get(selection);
            if(!s.getTitulo().contains(jTextField1.getText().toLowerCase())){
                System.out.print("Entra al if");
                selection++;                
            }
            else{
                System.out.print("Entra al else");
               
                            
                capitulos=s.getCapitulos();            
                jSinopsis.setText("Sinopsis: "+"\n"+s.getSinopsis());            
                jImagen.setIcon(s.getImagen());
                jActor.setText("Actores: "+s.getActores());
                jAnno.setText("Año: "+s.getAnno());
                jTemporada.setText("Nº temporadas: "+s.getTemporadas());
                jGenero.setText("Género: "+s.getGenero());
                jTitulo.setText("Titulo: "+s.getTitulo());  
                jPuntuacion3.setText("Puntuación: " + s.getPuntuacion());
                for(Capitulo c:capitulos){
                  modelo2.addElement(c.getTitulo());                
                }
                selection++;   
                    }
    
        }
        
    }//GEN-LAST:event_listaBusquedaValueChanged

    private void listaCapitulosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCapitulosValueChanged
        
        int capit=listaCapitulos.getSelectedIndex();
        if (capit!=-1) {
            Capitulo c = capitulos.get(capit);
            jDuracionCap.setText("Duración: "+c.getDuracion()+" min.");
        }
            
        
    }//GEN-LAST:event_listaCapitulosValueChanged

    private void btnAddFavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddFavMouseClicked
        // TODO add your handling code here:

        int selection = listaBusqueda.getSelectedIndex();
        if (selection != -1) {
            Serie s = series.get(selection);
            
            try {
            
            File file1 = new File("ficheros/listaFav/listaSeriesFav"+leerDniTemp()+".dat");
            
            // Si los archivos no existen se crean
                if (!file1.exists()) {
                file1.createNewFile();
            }
            } catch (IOException e) {
            e.printStackTrace();
            }
            
            if (seriesFav.isEmpty()) {
                    seriesFav.add(s);
                    ordenarAnno();
                    GuardarLeerFicheros.guardarSerieListaFav(leerDniTemp());
            }
            
            for (Serie ser: seriesFav) {
                
                if (!ser.getTitulo().equals(s.getTitulo())) {
                    seriesFav.add(s);
                    ordenarAnno();
                    GuardarLeerFicheros.guardarSerieListaFav(leerDniTemp());
                }
            }

        }
    }//GEN-LAST:event_btnAddFavMouseClicked

    private void btnCalificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalificarMouseClicked
        // TODO add your handling code here:
        int selection = listaBusqueda.getSelectedIndex();
        Double punt;
        
        if (selection != -1) {
            Serie s = series.get(selection);
            series.remove(selection);
            
            if (s.getPuntuacion().equals("")) {
                punt = Double.parseDouble(jPuntuacion.getText());
                s.setPuntuacion(jPuntuacion.getText());
                series.add(s);
                ordenarAnno();
                GuardarLeerFicheros.guardarDatosSeries();
                jPuntuacion3.setText("Puntuación: "+punt);
                jPuntuacion.setText("");
            } else {
                punt = (Double.parseDouble(s.getPuntuacion()) + Double.parseDouble(jPuntuacion.getText())) / 2;
                s.setPuntuacion(punt.toString());
                series.add(s);
                ordenarAnno();
                GuardarLeerFicheros.guardarDatosSeries();
                jPuntuacion3.setText("Puntuación: "+punt);
                jPuntuacion.setText("");
            }
        }
    }//GEN-LAST:event_btnCalificarMouseClicked


    
    public static String leerDniTemp() {
        String dni = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader("ficheros/archivoTemporal.dat"));
            String temp = "";
            String bfRead;
            while ((bfRead = br.readLine()) != null) {
                temp = temp + bfRead;
            }
            dni = temp;
            
        } catch (Exception e) {
        }
        return dni;
    }
    
    public void ordenarAnno() {
        Collections.sort(series, new Comparator<Serie>() {            
            @Override
            //Ordenamos el array series por año, de mayor a menor
            public int compare(Serie p1, Serie p2) {
                    //Comparamos p2 con p1
                    return new Integer(Integer.parseInt(p2.getAnno())).compareTo(new Integer(Integer.parseInt(p1.getAnno())));
            }
        });
    }
    
    public void ordenarPuntuacion() {
        Collections.sort(series, new Comparator<Serie>() {            
            @Override
            //Ordenamos el array series por puntuación, de mayor a menor
            public int compare(Serie p1, Serie p2) {
                    //Comparamos p2 con p1
                    return new Double(Double.parseDouble(p2.getPuntuacion())).compareTo(new Double(Double.parseDouble(p1.getPuntuacion())));
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFav;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCalificar;
    private javax.swing.JLabel jActor;
    private javax.swing.JLabel jAnno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jDuracion;
    private javax.swing.JLabel jDuracionCap;
    private javax.swing.JLabel jGenero;
    private javax.swing.JLabel jImagen;
    private javax.swing.JTextField jPuntuacion;
    private javax.swing.JLabel jPuntuacion3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jSinopsis;
    private javax.swing.JLabel jTemporada;
    private javax.swing.JLabel jTemporadas;
    private javax.swing.JLabel jTemporadas1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JList<String> listaBusqueda;
    private javax.swing.JList<String> listaCapitulos;
    private javax.swing.JPanel panelBase;
    private poo.Interfaces.PanelTransparente panelTransparente1;
    // End of variables declaration//GEN-END:variables
}
