/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sql_conection;

/**
 *
 * @author david
 */
public class Login extends javax.swing.JFrame {

    
          String user, pass;
           
         
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
          

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreo = new javax.swing.JTextField();
        labelContrasena = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelSubTitulo = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        labelContrasena1 = new javax.swing.JLabel();
        btnConfirmar1 = new javax.swing.JLabel();
        CorreoInvalido = new javax.swing.JLabel();
        ContrasenaInvalido = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();

        txtCorreo.setBackground(new java.awt.Color(102, 102, 102));
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        labelContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena.setText("Contraseña:");

        btnConfirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmarKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        labelSubTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelSubTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelSubTitulo.setText("Iniciar sesión");
        labelSubTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSubTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSubTituloMouseClicked(evt);
            }
        });

        labelCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        labelCorreo.setText("Usuario:");

        txtCorreo1.setBackground(new java.awt.Color(102, 102, 102));
        txtCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo1.setBorder(null);
        txtCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreo1ActionPerformed(evt);
            }
        });

        labelContrasena1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelContrasena1.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena1.setText("Contraseña:");

        btnConfirmar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmar1.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar1.setText("Confirmar");
        btnConfirmar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmar1MouseClicked(evt);
            }
        });
        btnConfirmar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConfirmar1KeyPressed(evt);
            }
        });

        CorreoInvalido.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CorreoInvalido.setForeground(new java.awt.Color(255, 0, 0));
        CorreoInvalido.setText("El usuario introducido no es valido");
        CorreoInvalido.setVisible(false);

        ContrasenaInvalido.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ContrasenaInvalido.setForeground(new java.awt.Color(255, 0, 0));
        ContrasenaInvalido.setText("La contraseña introducida no es valida");
        ContrasenaInvalido.setVisible(false);

        txtContraseña.setBackground(new java.awt.Color(102, 102, 102));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar1)
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContrasenaInvalido)
                    .addComponent(CorreoInvalido)
                    .addComponent(labelContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubTitulo)
                    .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addComponent(txtCorreo1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelSubTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorreoInvalido)
                .addGap(40, 40, 40)
                .addComponent(labelContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContrasenaInvalido)
                .addGap(85, 85, 85)
                .addComponent(btnConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        labelCorreo.getAccessibleContext().setAccessibleName("Usuario");
        txtContraseña.getAccessibleContext().setAccessibleName("txtContraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelSubTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSubTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSubTituloMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreo1ActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked

       
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnConfirmarKeyPressed

    private void btnConfirmar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmar1MouseClicked
 
        user = txtCorreo1.getText();
        pass = txtContraseña.getText();
        PanelConsultas pc = new PanelConsultas(this.user,this.pass);
        
        //Aqui seleccionamos el user que ha introducido, 
        switch (user) {
            case "administrador"://CASO ADMINISTRADOR
                if (pass.equals("admin")) {
                    esCorrecto(user, pass);
                    
                   
                    pc.setVisible(true);
                     this.dispose();
                } else {
                    esIncorrecto();
                    
                    this.dispose();
                }
                break;
            case "gestor"://CASO GESTOR
                if (pass.equals("gestor")) {
                    esCorrecto(user, pass);
                   
                   
                    
                     this.dispose();
                     pc.setVisible(true);
                } else {
                    esIncorrecto();
                    this.dispose();
                    
                }
                break;
            case "invitado"://CASO RECEPCIONISTA
                if (pass.equals("invitado")) {
                    esCorrecto(user, pass);
                    
                    this.dispose();
                    pc.setVisible(true);
                } else {
                    esIncorrecto();
                    
                    this.dispose();
                }
                break;
            case "cliente"://CASO GENERAL
                if (pass.equals("cliente")) {
                    esCorrecto(user, pass);
                   
                    
                    pc.setVisible(true);
                    this.dispose();
                } else {
                    esIncorrecto();
                   
                    this.dispose();
                }
                break;
            default://LA MAYORIA DE LOS CASOS SON
                esIncorrecto();
                
               
                break;
        
                                                    
        }
       
    }//GEN-LAST:event_btnConfirmar1MouseClicked

    private void btnConfirmar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmar1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnConfirmar1KeyPressed

    public void esCorrecto(String user,String  pass) {
        if(user.equals("postgres")){
            
            this.setUser(user);
            this.setPass(pass);
            
            
        }else{
            
            this.setUser(user);
            this.setPass(pass);
            
            
        }
    }
    
    public void esIncorrecto() {//Si el inicio de sesion no es correcto
        
        CorreoInvalido.setVisible(true);
        ContrasenaInvalido.setVisible(true);
        
        
    }

    public Login(String user, String pass) {
        this.user = user;
        this.pass = pass;
        
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

  

  String usuario(){
         user = txtCorreo1.getText();
         return user;
    }
    String pass(){
        pass = txtContraseña.getText();
        return pass;
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContrasenaInvalido;
    private javax.swing.JLabel CorreoInvalido;
    private javax.swing.JLabel btnConfirmar;
    private javax.swing.JLabel btnConfirmar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelContrasena1;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelSubTitulo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreo1;
    // End of variables declaration//GEN-END:variables
}
